version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: composer/composer
    versions:
    - 1.10.20
    - 1.10.21
  - dependency-name: symfony/console
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/mime
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: composer/xdebug-handler
    versions:
    - 1.4.5
  - dependency-name: symfony/event-dispatcher
    versions:
    - 5.2.3
  - dependency-name: symfony/finder
    versions:
    - 5.2.3
  - dependency-name: symfony/options-resolver
    versions:
    - 5.2.3
  - dependency-name: symfony/http-client
    versions:
    - 5.2.2
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-mbstring
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-intl-idn
    versions:
    - 1.22.0
  - dependency-name: league/container
    versions:
    - 3.3.3
